version: '2'

services:
  # INTVOICE containers ------------------------------------------
  test-intvoice-php:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-main-php
    links:
        - test-intvoice-redis
        - test-intvoice-www
        - test-intvoice-mysql
        - test-intvoice-selenium
        - test-banking-www
    depends_on:
      - test-intvoice-mysql
    volumes:
      - ${INTVOICE_PATH}/:/var/www/html
    env_file:
      - ${INTVOICE_PATH}/.env.docker.testing
    environment:
      - DB_DATABASE=${INTVOICE_TEST_DB_DATABASE}
      - APP_URL=http://test-intvoice-www

  test-intvoice-php-small:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-main-php
    links:
        - test-intvoice-redis
        - test-intvoice-mysql
    volumes:
      - ${INTVOICE_PATH}/:/var/www/html
    env_file:
      - ${INTVOICE_PATH}/.env.docker.testing
    environment:
      - DB_DATABASE=${INTVOICE_TEST_DB_DATABASE}
      - APP_URL=http://test-intvoice-www
    depends_on:
      - test-intvoice-mysql

  test-intvoice-main-selenium: &TEST_INTVOICE_MAIN_SELENIUM
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  test-intvoice-selenium:
    image: selenium/standalone-chrome
    ports:
      - "${SELENIUM_PORT}:4444"
    links:
      - test-intvoice-www
    volumes:
      - /dev/shm:/dev/shm
  
  test-intvoice-www:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-main-www
    links:
      - test-intvoice-php-small:php-fpm-host
    volumes:
      - ${INTVOICE_PATH}/:/var/www/html
      - ${INTVOICE_PATH}/docker/logs/nginx:/var/log/nginx

  test-intvoice-mysql:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-main-mysql
    volumes:
      - ${INTVOICE_PATH}/mysql:/var/lib/mysql
    environment:
      DB_DATABASE: ${INTVOICE_TEST_DB_DATABASE}
      DB_USERNAME: ${INTVOICE_TEST_DB_USERNAME}
      DB_PASSWORD: ${INTVOICE_TEST_DB_PASSWORD}
      DB_ROOT_PASSWORD: ${INTVOICE_TEST_DB_ROOT_PASSWORD}
    privileged: true

  test-intvoice-redis:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-redis

  test-intvoice-packages:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-main-packages
    volumes:
      - ${INTVOICE_PATH}/:/workspace

  # BANKING containers ------------------------------------------
  test-banking-php:
    image: innolend/php:1.0
    volumes:
      - ${INTVOICE_PATH}/fake_banking/:/var/www/html

  test-banking-www:
    image: innolend/nginx:1.0
    links:
      - test-banking-php:php-fpm-host
    volumes:
      - ${INTVOICE_PATH}/fake_banking/:/var/www/html

volumes:
    mysql:
        driver: "local"
