echo "BANKING building composer ..."
docker-compose -f ../BANKING/docker-compose.yml run banking-php sh -c "composer install"
echo "INTVOICE building composer ..."
docker-compose -f ../INTVOICE/docker-compose.yml run intvoice-php sh -c "composer install"
echo "VERIFICATION building composer ..."
docker-compose -f ../VERIFICATION/docker-compose.yml run verification-php sh -c "composer install"

echo "INTVOICE building node modules && gulp ..."
docker-compose -f ../INTVOICE/docker-compose.yml run intvoice-packages sh -c "yarn install && npm link node-sass && gulp"
echo "VERIFICATION building node modules && gulp ..."
docker-compose -f ../VERIFICATION/docker-compose.yml run intvoice-packages sh -c "yarn install && npm link node-sass && gulp"
echo "UNDERWRITER building node modules && gulp ..."
docker-compose -f ../UNDERWRITER/docker-compose.yml run intvoice-packages sh -c "yarn"

echo "BANKING rebuilding cache ..."
docker-compose -f ../BANKING/docker-compose.yml run --rm banking-php sh -c "php artisan optimize --force && php artisan config:cache && php artisan route:cache"
echo "INTVOICE rebuilding cache ..."
docker-compose -f ../INTVOICE/docker-compose.yml run --rm intvoice-php sh -c "php artisan optimize --force && php artisan config:cache && php artisan route:cache"
