version: '2'

services:
  # INTVOICE containers ------------------------------------------
  test-intvoice-php:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-main-php
    links:
        - test-intvoice-redis
        - test-intvoice-www
        - test-intvoice-mysql
        - test-intvoice-selenium
        - test-banking-www
    depends_on:
      - test-intvoice-mysql
    volumes:
      - ${INTVOICE_PATH}/:/var/www/html
    env_file:
      - ${INTVOICE_PATH}/.env.testing
    environment:
      - DB_DATABASE=${INTVOICE_TEST_DB_DATABASE}
      - APP_URL=http://test-intvoice-www

  test-intvoice-php-small:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-main-php
    links:
        - test-intvoice-redis
        - test-intvoice-mysql
    volumes:
      - ${INTVOICE_PATH}/:/var/www/html
    env_file:
      - ${INTVOICE_PATH}/.env.testing
    environment:
      - DB_DATABASE=${INTVOICE_TEST_DB_DATABASE}
      - APP_URL=http://test-intvoice-www
    depends_on:
      - test-intvoice-mysql

  test-intvoice-selenium:
    image: selenium/standalone-chrome
    ports:
      - "${SELENIUM_PORT}:4444"
    links:
      - test-intvoice-www
    volumes:
      - /dev/shm:/dev/shm
  
  test-intvoice-www:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-main-www
    links:
      - test-intvoice-php-small:php-fpm-host
    volumes:
      - ${INTVOICE_PATH}/:/var/www/html
      - ${INTVOICE_PATH}/docker/logs/nginx:/var/log/nginx

  test-intvoice-mysql:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-main-mysql
    volumes:
      - ${INTVOICE_PATH}/mysql:/var/lib/mysql
    environment:
      DB_DATABASE: ${INTVOICE_TEST_DB_DATABASE}
      DB_USERNAME: ${INTVOICE_TEST_DB_USERNAME}
      DB_PASSWORD: ${INTVOICE_TEST_DB_PASSWORD}
      DB_ROOT_PASSWORD: ${INTVOICE_TEST_DB_ROOT_PASSWORD}
    privileged: true

  test-intvoice-redis:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-redis

  test-intvoice-packages:
    extends: 
      file: ${INTVOICE_PATH}/docker-compose.yml
      service: intvoice-main-packages
    volumes:
      - ${INTVOICE_PATH}/:/workspace

  # BANKING containers ------------------------------------------
  test-banking-php:
    extends: 
      file: ${BANKING_PATH}/docker-compose.yml
      service: banking-main-php
    links:
      - test-banking-mysql
      - test-banking-redis
    depends_on:
      - test-banking-mysql
    volumes:
      - ${BANKING_PATH}/:/var/www/html
    env_file:
      - ${BANKING_PATH}/.env.testing
    environment:
      - DB_DATABASE=${BANKING_TEST_DB_DATABASE}

  test-banking-www:
    extends: 
      file: ${BANKING_PATH}/docker-compose.yml
      service: banking-main-www
    links:
      - test-banking-php:php-fpm-host
    volumes:
      - ${BANKING_PATH}/:/var/www/html
      - ${BANKING_PATH}/docker/logs/nginx:/var/log/nginx
    env_file:
      - ${BANKING_PATH}/.env.testing

  test-banking-mysql:
    extends: 
      file: ${BANKING_PATH}/docker-compose.yml
      service: banking-main-mysql
    image: innolend/docker-mariadb
    volumes:
      - ${BANKING_PATH}/mysql:/var/lib/mysql
    environment:
      DB_DATABASE: ${BANKING_TEST_DB_DATABASE}
      DB_USERNAME: ${BANKING_TEST_DB_USERNAME}
      DB_PASSWORD: ${BANKING_TEST_DB_PASSWORD}
      DB_ROOT_PASSWORD: ${BANKING_TEST_DB_ROOT_PASSWORD}
    privileged: true

  test-banking-redis:
    extends: 
      file: ${BANKING_PATH}/docker-compose.yml
      service: banking-redis

  test-banking-packages:
    extends: 
      file: ${BANKING_PATH}/docker-compose.yml
      service: banking-main-packages
    volumes:
      - ${BANKING_PATH}/:/workspace

volumes:
    mysql:
        driver: "local"
